"""add manufacturer to medicines

Revision ID: 76da01300fe8
Revises: 
Create Date: 2026-06-15 16:06:09.921074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76da01300fe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=200), nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
